### ISSUE TITLE
Not checking for existence of cache file before writing

### ISSUE THREAD

**Issue by botherder** [blockadeio/analyst_toolbench#3]
At the first execution of `blockade ioc --single X` it seems like writing to a cache file isn't properly checked:

```
Traceback (most recent call last):
  File "/usr/local/bin/blockade", line 11, in <module>
    load_entry_point('blockade-toolkit==1.0.0', 'console_scripts', 'blockade')()
  File "/usr/local/lib/python2.7/dist-packages/blockade_toolkit-1.0.0-py2.7.egg/blockade/cli/client.py", line 40, in main
    response = process_ioc(args)
  File "/usr/local/lib/python2.7/dist-packages/blockade_toolkit-1.0.0-py2.7.egg/blockade/cli/client.py", line 17, in process_ioc
    response = client.add_indicators([args.single])
  File "/usr/local/lib/python2.7/dist-packages/blockade_toolkit-1.0.0-py2.7.egg/blockade/libs/indicators.py", line 58, in add_indicators
    cache_items(to_send['indicators'])
  File "/usr/local/lib/python2.7/dist-packages/blockade_toolkit-1.0.0-py2.7.egg/blockade/common/utils.py", line 55, in cache_items
    written = [x.strip() for x in open(file_path, 'r').readlines()]
IOError: [Errno 2] No such file or directory: '/home/USER/.config/blockade/cache.txt'
```

A touch to the path fixed it.

**Comment by 9b** [comment]
Placed a file check prior to the append that will write the file if it doesn't already exist.
